name: Update Stock Price

on:
  schedule:
    # Run at 16:30 UTC (after London market close) every weekday
    - cron: '30 16 * * 1-5'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-price:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Update stock price
        run: python scripts/update_share_price.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/share-price.json
          git commit -m "Update stock price" || exit 0
          git push 